language: php

jobs:
  fast_finish: true
  include:
    - php: 5.4
      dist: trusty
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 5.4
      dist: trusty
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 5.5
      dist: trusty
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 5.5
      dist: trusty
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 5.6
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 5.6
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 7.0
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 7.0
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 7.1
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 7.1
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 7.2
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 7.2
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 7.3
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 7.3
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: 7.4
      env: COMPOSER_OPTIONS=--prefer-stable
    - php: 7.4
      env: COMPOSER_OPTIONS=--prefer-lowest
    - php: nightly
      env: COMPOSER_OPTIONS=--prefer-stable --ignore-platform-reqs
    - php: nightly
      env: COMPOSER_OPTIONS=--prefer-lowest --ignore-platform-reqs
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update "php-coveralls/php-coveralls:^1 | ^2"
  - travis_retry composer update --no-interaction --prefer-dist --no-progress --no-suggest $COMPOSER_OPTIONS
  - if [ -f vendor/bin/coveralls ]; then ln -s coveralls vendor/bin/php-coveralls; fi

before_script:
  - mkdir -p build/logs

script:
  - composer lint
  - composer phpcs -- --warning-severity=0
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
