language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 5.5
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: hhvm
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_FLAGS --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/aaf2dd731ff9d9bf7710'
    on_success: change
    on_failure: always
    on_start: false
